insert into OCRD(id,bpCode,bpName) values(1,N'C001',N'C001');
insert into OCRD(id,bpCode,bpName) values(2,N'C002',N'C0022');
insert into OITM(id,itemCode,itemName) values(1,N'I001',N'I001');
insert into OITM(id,itemCode,itemName) values(2,N'I002',N'I002');
insert into ORDR(id,bpId,remarks,docTotal) values(1,1,N'desc1', 100.99);
insert into ORDR(id,bpId,remarks,docTotal) values(2,1,N'desc2', 69);
insert into RDR1(id,parentId,itemId) values(1,1,1);
insert into RDR1(id,parentId,itemId) values(2,1,2);
insert into RDR1(id,parentId,itemId) values(3,1,1);
insert into RDR1(id,parentId,itemId) values(4,2,1);