insert into OCRD(id,bpCode,bpName) values(1,N'C001',N'C001');
insert into OCRD(id,bpCode,bpName) values(2,N'C002',N'C0022');
insert into OITM(id,itemCode,itemName) values(1,N'I001',N'I001');
insert into OITM(id,itemCode,itemName) values(2,N'I002',N'I002');
insert into OITM(id,itemCode,itemName) values(3,N'I003',N'I003');
insert into ORDR(id,bpId,remarks,docTotal, docStatus) values(1,1,N'desc1', 100.99, 'O');
insert into ORDR(id,bpId,remarks,docTotal, docStatus) values(2,1,N'desc2', 69, 'C');
insert into RDR1(id,parentId,itemId,price,quantity,lineTotal) values(1,1,1,1.1,1.2,1.3);
insert into RDR1(id,parentId,itemId,price,quantity,lineTotal) values(2,1,2,2.1,2.2,2.3);
insert into RDR1(id,parentId,itemId,price,quantity,lineTotal) values(3,1,1,3.1,3.2,3.3);
insert into RDR1(id,parentId,itemId,price,quantity,lineTotal) values(4,2,1,4.1,4.2,4.3);
insert into OADM(id,compnyName,sumDec,qtyDec,priceDec,rateDec,percentDec,measureDec) values(1,'US01',1,2,3,4,5,6);
